baseURL = "https://kenstevens.github.io/"
languageCode = "en-us"
title = "Ken's Blog"
theme = "blank"
publishDir = "kenstevens.github.io"

[menu]

[[menu.main]]
  identifier = "about"
  name = "About me"
  url = "/about/"
  weight = 110
